### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by Kristofferson777** [hanxingjian/GroundLink#7]
I was wondering how the data files are supposed to be organized? Do take the subject files like s007 from the moshpp, fbx, force, AMASS and put them in one s007 folder? And should this be contained in a "Data" folder.

**Comment by Kristofferson777** [comment]
I managed to get the file structure to work but now I'm having issues Predict.ipynb file. 

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
<img width="829" alt="predict isse" src="https://github.com/user-attachments/assets/1986e7e3-a06e-42d9-aff3-8f3bca635252">

**Comment by Kristofferson777** [comment]
I finally managed to get to the last step of the visualizer but am running into a smplx error
![image](https://github.com/user-attachments/assets/8eb0913d-1ff3-4a86-af93-37f6938076df)

**Comment by Kristofferson777** [comment]
I downloaded the third smplx link on the smplx website but I'm not sure why it's saying smplx does not exist. 
I also made sure to change to smplx in the aitviewer files but the line 205 we are supposed to change is no longer there in aitviewer so I changed it in the other lines that have mode_type for a smpl type.

**Comment by Kristofferson777** [comment]
I finally got all the files properly setup and managed to run visualize_target_pred_s7.py but ran into a error. Below is an image of the error:
![image](https://github.com/user-attachments/assets/ff02ea30-92ee-48cb-bb17-2473325cf0bc)

**Comment by Kristofferson777** [comment]
(groundlink) C:\Users\Chris\GroundLink\Visualization>python visualize_target_pred_s7.py
Data keys available: ['trans', 'gender', 'mocap_framerate', 'betas', 'poses']
  1781 poses of size  165.
  1781 trans of size    3.
     1 shape of size   16.
Gender female
FPS 250.0
Traceback (most recent call last):
  File "C:\Users\Chris\GroundLink\Visualization\visualize_target_pred_s7.py", line 53, in <module>
    seq_amass = SMPLSequence.from_amass(
  File "C:\Users\Chris\GroundLink\Visualization\aitviewer\aitviewer\renderables\smpl.py", line 241, in from_amass
    return cls(
  File "C:\Users\Chris\GroundLink\Visualization\aitviewer\aitviewer\renderables\smpl.py", line 161, in __init__
    global_oris = local_to_global(
  File "C:\Users\Chris\GroundLink\Visualization\aitviewer\aitviewer\utils\utils.py", line 342, in local_to_global
    if parents[j] < 0:
IndexError: index 22 is out of bounds for axis 0 with size 22

**Comment by Kristofferson777** [comment]
Fixed more issues, the one above was an issue using the new version of aitviewer. I reverted to a previous version I believe 1.12.0 and now I'm having this issue.
![image](https://github.com/user-attachments/assets/1a3afa38-f99f-4e64-bb49-8ebccb76a325)

**Comment by Kristofferson777** [comment]
seems to be a simplx merge error
